### ISSUE TITLE
GitHub userscripts

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/todo#12]
I use GitHub everyday. Even though it's really good, there are still a lot of stuff that could be improved. I'm tired of waiting on GitHub to fix things, I can code Jqueri, so why not do it myself.

- [x] <del>Make the black branch thingies on Pull Requests, that looks like buttons, actually clickable.</del>
http://skratchdot.com/projects/github-pull-request-links.user.js/

- [x] Make code use the `tab-size` CSS rule.

- [x] Hide noise

Any suggestions?

**Comment by psyrendust** [comment]
> Hide noise

@sindresorhus I created this Chrome extension ([GitHub Review Filters](https://chrome.google.com/webstore/detail/github-review-filters/cdfbkmackojgkcohdfikiablcecbcdfa)) to help reduce the noise at my last job. Let me know if it helps you out.

**Comment by sindresorhus** [comment]
I finally did it: https://github.com/sindresorhus/refined-github
