### ISSUE TITLE
write some vim plugins

### ISSUE THREAD

**Issue by piemelaah** [sindresorhus/todo#20]
Vim has an awesome, all open-source, community so this open source guru should be contributing to that :)

I'd love to see some vim plugins from you. Somebody like you is very welcome in our community.

**Comment by sindresorhus** [comment]
Hah, thanks, but I'm currently quite happy with Sublime Text, so don't see this happening in the foreseeable future :)

**Comment by piemelaah** [comment]
@sindresorhus why, it would save you so much time?

**Comment by sindresorhus** [comment]
It probably would, but I would lose so much time until I got productive and I don't have time to invest in that right now. I'd rather focus on making things right now ;)

**Comment by piemelaah** [comment]
A few months of digging into it and you'll be more productive for the rest of your life... You cared about productivity and developer tooling, right? You created yeoman to save minutes to scaffold projects, why not to save time here too?

**Comment by arthurvr** [comment]
@piemelaah I personally totally agree that Vim is quite awesome but remember that it's just a personal taste :)

Also what @sindresorhus said about spending time developing things rather than learning an editor is quite valid :+1:

**Comment by piemelaah** [comment]
Then my answer is, you're a jerk, @sindresorhus. And you said you cared about tooling. Very disappointed.

**Comment by piemelaah** [comment]
YOU'RE A FAGGOOTT!
