### ISSUE TITLE
Convert all my CLIs to `meow`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/todo#22]
Still a lot of modules that are not using [`meow`](https://github.com/sindresorhus/meow).

Help appreciated :)

https://github.com/search?utf8=%E2%9C%93&q=user%3Asindresorhus+indexOf%28%27--help%27%29&type=Code&ref=searchresults

**Comment by arthurvr** [comment]
Seems like @kevva is doing great :p

**Comment by kevva** [comment]
Should be fixed now.

**Comment by sindresorhus** [comment]
Oh wow. Awesome!

![tumblr_nifcd3fiwt1rsdpaso1_500](https://cloud.githubusercontent.com/assets/170270/8265035/624d4a72-16f0-11e5-8ea6-2a9f51abee91.gif)

**Comment by kevva** [comment]
wow, scary gif, hah.
