### ISSUE TITLE
All the maths

### ISSUE THREAD

**Issue by gaborcsardi** [sindresorhus/todo#23]
CF `https://github.com/node-forward/discussions/issues/1`

You have been working on this already, anyway. :) So just finish the job please. :)

To make it more concrete:
- Work out a way to do math in JS, i.e. to do more or less everything the `base` R package does. Say, manipulation of vectors, matrices, arithmetic.
- Make an environment for interactive data exploration. Something like RStudio for R (http://www.rstudio.com), but cooler. Maybe it is possible on top of Atom.

**Comment by sindresorhus** [comment]
I would really like to see this too, but that's probably over my head. I'm not a math person.

Can you open it in https://github.com/sindresorhus/module-requests and I'll do my best to get some eyes on it ;)
