### ISSUE TITLE
data structures

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/todo#24]
I miss a good set of modules for implement traditional data structures. It's true that [collectionjs](http://www.collectionsjs.com/) it's ok, but in special I miss trees and more complex structures.

https://en.wikipedia.org/wiki/List_of_data_structures

**Comment by sindresorhus** [comment]
Can you open this here instead https://github.com/sindresorhus/module-requests ?

**Comment by Kikobeats** [comment]
:ok_hand:
