### ISSUE TITLE
Finish my Poll app using Meteor

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/todo#9]
I started a real-time Meteor app for simple collaborative polls with Markdown support.

As many other projects, I never managed to do the last 30%...

Finish it! Dude, seriously.

Will be open sourced of course.

**Comment by kevva** [comment]
I guess this can be closed? :)))

**Comment by sindresorhus** [comment]
Yeah... Still have it and it's working, but I don't seem to have time to finish it.
